-- dbt model configuration
{{ "{{" }}
    config(
        enabled=true,
        dataset="{{ source_view.split('.')[1] }}",
        alias="{{ source_view.split('.')[2] }}",
        materialized="view"
    )
{{ "}}" }}

-- Original BigQuery view: {{ source_view }}
-- Generated by bq2dbt at {{ timestamp }}

{{ sql_definition }}